numbers = input()
numbers_as_int = list(map(int, numbers.split()))
print(f"The minimum number is {min(numbers_as_int)}")
print(f"The maximum number is {max(numbers_as_int)}")
print(f"The sum number is: {sum(numbers_as_int)}")